Repository LLNL/Elemental, pull requests merged in 2019-01, with the labels that each got.

#61 Matrices force leading dim to be greater than zero
  include/El/core/AbstractMatrix.hpp
  include/El/core/Matrix/impl_cpu.hpp
  include/El/core/Matrix/impl_gpu.hpp
Labels: bug, review requested

#64 update to cuda toolkit handling to fix cuda 10
  CMakeLists.txt
  cmake/configure_files/HydrogenConfig.cmake.in
Labels: bug, build, enhancement, review requested

#66 remove compute functions from Matrix
  include/El/core/Matrix/decl.hpp
  include/El/core/Matrix/impl_cpu.hpp
Labels: enhancement, review requested

#65 FP16 resurrected
  CMakeLists.txt
  cmake/configure_files/HydrogenConfig.cmake.in
  cmake/configure_files/hydrogen_config.h.in
  cmake/modules/FindHALF.cmake
  include/El/core.hpp
  include/El/core/Element/decl.hpp
  include/El/core/Element/impl.hpp
  include/El/core/Matrix/impl_cpu.hpp
  include/El/core/imports/cuda.hpp
Labels: enhancement, review requested
