Repository LLNL/Elemental, pull requests merged in 2021-03, with the labels that each got.

#114 Tweaks to the ROCm CMakery
  CMakeLists.txt
  cmake/configure_files/HydrogenConfig.cmake.in
Labels: build, enhancement, review requested

#118 Avoid unnecessary memory allocation in scatter function
  include/El/blas_like/level1/Copy/Scatter.hpp
Labels: bug, review requested

#119 add support for v1.0.0 of Aluminum; keep v0.7.0 support, too
  CMakeLists.txt
Labels: build, review requested
